name: Build dylib

on: push

jobs:
  build:
    runs-on: macos-14   # 使用 macOS 14 环境，自带 Xcode 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile dylib
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libInject
          path: libInject.dylib
